### ISSUE TITLE
Cant connect to database

### ISSUE THREAD

**Issue by moritzsproll** [pgRouting/pgRoutingLayer#133] opened 2020-12-01 23:21 UTC
I have a connection to the database with postgis, but i cant connect the database with pgrouting. (refer to screenshots) The field where i should put the database is grey. The SQL-Query in the DB Manager "SELECT pgr_version from pgr_version();" is giving me a result. My version is 3.00-rc1. 
The python console is giving that error if i click the green reload button:  
 File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 1255, in openHelp
              db = self.actionsDb[dbname].connect()
             KeyError: ''
             
Im just a starter with pgrouting, so excuse me if it's not a bug and maybe help me to solve my problem :D 

![frage1](https://user-images.githubusercontent.com/75342047/100808110-d49d7f00-3433-11eb-9549-5ee931c03ec0.JPG)
![frage2](https://user-images.githubusercontent.com/75342047/100808113-d5ceac00-3433-11eb-8018-71b3d8e35972.JPG)

**Comment by cayetanobv** [comment] 2020-12-08 15:16
Hi @moritzsproll . This error is probably because you are using the version of the plugin at QGIS-hub with pgRouting v3 (there are some incompatibilities). We are preparing a new version these days so you can wait for this new upgrade to test again (the new version probably will be available this week).

**Comment by moritzsproll** [comment] 2020-12-10 10:22
@cayetanobv Thanks a lot for your help ! Can I get the updated version out of the QGIS plugin "store" or should I download it manually from github and put it in the plugins folder of QGIS ?

**Comment by cayetanobv** [comment] 2020-12-10 10:36
You can take the code from github for now and test it. Soon you can have the new version in plugin hub. Remember to change folder name to `pgRoutingLayer`.

**Comment by moritzsproll** [comment] 2020-12-10 15:53
@cayetanobv i downloaded the plugin and renamed the folder, but I am getting an error. Where exactly should i change the name to pgRoutingLayer ? Thanks for your help !

**Comment by moritzsproll** [comment] 2020-12-20 21:33
@cayetanobv i almost tried everything, but im still getting this error. I think i named the folder correctly. Everything looks similar to the directory of other installed plugins. 
![error](https://user-images.githubusercontent.com/75342047/102724904-322a3a80-4313-11eb-919c-9572858ddbfd.JPG)
...

**Comment by andyprasetya** [comment] 2021-03-23 06:01
@cayetanobv : I think it is not a bug. Well, database configuration may have some caveats, and so far I do not have any trouble for operating pgRoutingLayer.

Here is my environment: I use QGIS 3.16.4 Hannover (LTR) and pgRoutingLayer 3.0.1, to be connected with PostgreSQL 13 + PostGIS 3.1.0. When configuring database connection via Data Source Manager, make sure DB username and password are stored.

![db-config](https://user-images.githubusercontent.com/765224/112099441-16665700-8bd6-11eb-8612-c6d227193920.png)

I noticed that whenever I stored them, and refresh the connection list in pgRoutingLayer, the database connection would appear successfully. If I create another connection and not store the username and password, it will never be listed in pgRoutingLayer.

I hope this will help.

**Comment by andyprasetya** [comment] 2021-03-23 07:14
Addition: Perhaps it is closely related to [this #44 issue](https://github.com/pgRouting/pgRoutingLayer/issues/44).

**Comment by jonath35** [comment] 2022-09-23 14:50
After having stored username and passaword I ve got "definition of service "NULL" not found"
qgis 3.22.5

**Comment by sanak** [comment] 2022-09-23 15:29
@jonath35 
> After having stored username and passaword I ve got "definition of service "NULL" not found" qgis 3.22.5

Thanks for information.
I encountered the same issue, but I couldn't reproduce the error after some operation (which I forgot it...).

By the way, we published pgRoutingLayer `3.0.2`, so could you try to upgrade the plugin, then check the connection again ?
In the latest version, error message will be shown in `Log Messsages` panel's `pgRouting Layer` tab.
![qgis-log-message-pgrouting-layer](https://user-images.githubusercontent.com/629923/191997337-4d110ffa-f85f-4985-9410-5fc370b14cb1.png)

**Comment by jonath35** [comment] 2022-09-26 07:36
connection is ok with pgroutinglayer 3.0.2

Howerver, the Vids returned in "Arguments" are wrongs. not from "ways_vertices_pgr" nor "ways"..

Thanks

**Comment by sanak** [comment] 2022-09-30 02:59
@jonath35 Okay, thanks for confirmation!

About directed option issue, I will check it a bit.

**Comment by sanak** [comment] 2022-09-30 15:20
@jonath35 I could reproduce the "directed" error, so I created the issue for that (https://github.com/pgRouting/pgRoutingLayer/issues/144).

Original issue (db connection) seems to be solved, so I close this issue.

**Closed by sanak** 2022-09-30 15:20 UTC
Labels: bug
